version: '3'

services:
  postgres:
    image: 'postgres:latest'
    network_mode: host
    env_file: ../.env
    logging:
      driver: none

  redis:
    image: 'redis:latest'
    network_mode: host
    env_file: ../.env
    logging:
      driver: none
