version: "3"

services:
  postgres:
    image: "postgres:latest"
    network_mode: bridge
    env_file: ../.env
    ports:
      - "5432:5432"
    logging:
      driver: none
  redis:
    image: "redis:latest"
    network_mode: bridge
    env_file: ../.env
    ports:
      - "6379:6379"
    logging:
      driver: none
